### ISSUE TITLE
only a question :)

### ISSUE THREAD

**Issue by KiuviGonka** [hsdn/npc-summoner#2]
Hello, sorry to write here, it is not a fault, it is more a question.
Is there any way to indicate in the index or in a file, the opcode of the definition that you want to add?
Something similar to what you do in this mod, where you add your own version of C_REQUEST_CONTRACT with the option :mod.dispatch.addDefinition("C_REQUEST_CONTRACT", 50.
Thanks in advance for any information you can give me.
![image](https://user-images.githubusercontent.com/90014929/151401307-f79c6041-9b2f-4bad-b2f2-b9ce80b93764.png)

**Comment by jk-q** [comment]
Hi. You can use for adding definition (example code):
```js
mod.dispatch.addDefinition("C_REQUEST_EVENT_MATCHING_TELEPORT", 0, [
	["unk1", "uint32"],
	["quest", "uint32"],
	["instance", "uint32"],
	["unk2", "uint32"],
	["unk3", "uint32"]
]);
```
and this for adding opcode:
```js
mod.dispatch.addOpcode("C_REQUEST_EVENT_MATCHING_TELEPORT", 26653); // GF v112.02
```

Check:
```js
mod.hook("C_REQUEST_EVENT_MATCHING_TELEPORT", 0, event => {
	console.log(event); 
});
```

**Comment by KiuviGonka** [comment]
lol I almost tried that, but I thought: it's too obvious it's not going to work xD. 
Resultados de traducción
thank you. Do you have any document that I can review of these methods and other existing ones? .
And finally I could abuse your knowledge a bit :) I need help with a mod... if you can write me to kiuvi#4545, thank you sir/miss

**Comment by jk-q** [comment]
you can dm me JKQ#5649
